version: 1
disable_existing_loggers: False
formatters:
  default:
    class: daktools.utils.json_log_formatter.JsonFormatter
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
  file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    filename: output/log.log
    when: midnight
    formatter: default
root:
  level: DEBUG
  handlers: [console, file_handler]
